# Term configuration
#set-option -g default-terminal screen-256color
set-option -g default-terminal xterm
set -g terminal-overrides 'xterm:colors=256'

set -g base-index 1

# Change to vi mode
setw -g mode-keys vi

# Setup `v` and `y` operators to start and yank selections (like Vim)
#bind-key -t vi-copy 'v' begin-selection
#bind-key -t vi-copy 'y' copy-pipe "reattach-to-user-namespace pbcopy"

# No delay for escape key press
set -sg escape-time 0

# stop autoupdating window title
set-option -g allow-rename off

# remap prefix to Control + a
set -g prefix C-Space
set -g prefix C-a
set -g prefix C-t
unbind C-b
bind C-a send-prefix
bind C-t send-prefix

# force a reload of the config file
unbind r
bind r source-file ~/.tmux.conf

# quick pane cycling
unbind ^A
bind ^A select-pane -t :.+

# Set Active window colour
set-window-option -g window-status-current-fg colour166 #orange
set-window-option -g window-status-current-bg colour222
set-window-option -g window-status-current-attr bright

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D 
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Maximize pane size
bind -n M-m resize-pane -Z

# Other usefule commands
bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"
bind C-c command-prompt -p "Command in new window: " "new-window '%%'"

# Status bar colour
set -g window-status-current-fg white
set -g window-status-current-bg blue

# Window switch
bind-key -n F1 select-window -t :1
bind-key -n F2 select-window -t :2
bind-key -n F3 select-window -t :3
bind-key -n F4 select-window -t :4
bind-key -n F5 select-window -t :5
bind-key -n F6 select-window -t :6

# share clipboard in vi-copy mode 
#bind -t vi-copy y copy-pipe 'xclip -in -selection clipboard'
